# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628d1c274853d51bec8180bd52d7024d7485febabc46445dedbcbd787b1c01016eb0950d6def0101108a4d2a90b786d7f5b21bb69c40d1895a1408434f3c03b2

test:
  secret_key_base: 048d7e8f1e0f98c661afc367ba7340f74794ad073d4bf2eaa0ca917e9aa1fafca2019bd950d0cd9aa898332291956ec5815a547f33920d79861e0202a601035d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
